version: '3'

services:
  postgres:
      image: postgres:14.1-alpine
      container_name: postgres
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      restart: always

  keycloak:
      image: quay.io/keycloak/keycloak:16.1.0
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: P@ssw0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      links: 
        - postgres
      depends_on:
        - postgres
      restart: always

  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    volumes: 
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/www/backend/logs/
    ports:
      - 80:80
    links:
      - keycloak


